version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8002"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8002"
    ports:
      - "8002:8002"  
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ZAIN
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  bot:
    build: .
    command: sh -c "sleep 5 && python manage.py bot"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
