# Generated by Django 5.1.5 on 2025-01-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
