# Generated by Django 5.1.5 on 2025-01-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('photo', models.ImageField(upload_to='photo', verbose_name='Фотография')),
                ('description', models.TextField(verbose_name='Описание работы (Требование, обязанности)')),
            ],
        ),
    ]
