# Generated by Django 5.1.5 on 2025-02-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_country_vacancy_created_vacancy_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='country_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='country_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание работы (Требование, обязанности)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание работы (Требование, обязанности)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Зарплата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Зарплата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название вакансии'),
        ),
    ]
