# Generated by Django 5.1.5 on 2025-01-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронная почта')),
                ('phone', models.IntegerField(verbose_name='Номер телеофона')),
                ('address', models.CharField(max_length=100, verbose_name='Адресс')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Инстаграмм')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Инстаграмм')),
            ],
        ),
    ]
