# Generated by Django 5.1.5 on 2025-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Зоголовок')),
                ('photo', models.ImageField(upload_to='photo', verbose_name='Фотография')),
            ],
        ),
    ]
