# Generated by Django 5.1.5 on 2025-01-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_title_photo2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Banner',
        ),
    ]
