# Generated by Django 5.1.5 on 2025-01-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_title_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннер'},
        ),
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
