# Generated by Django 5.1.5 on 2025-01-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_person', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('photo', models.ImageField(upload_to='photo', verbose_name='Фотография клиента')),
                ('description', models.TextField(verbose_name='Отзыв клиента')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
