# Generated by Django 5.1.5 on 2025-01-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_base_whatsapp'),
        ('base', '0007_reviews'),
    ]

    operations = [
    ]
