# Generated by Django 5.1.5 on 2025-02-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_base_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='телеграм'),
        ),
    ]
