# Generated by Django 5.1.5 on 2025-02-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_base_telegram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='name_of_person',
            new_name='name',
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Зоголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Зоголовок'),
        ),
        migrations.AddField(
            model_name='base',
            name='address_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='base',
            name='address_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Отзыв клиента'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Отзыв клиента'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя клиента'),
        ),
    ]
