# Generated by Django 4.2.10 on 2025-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_name_of_person_reviews_name_banner_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': ('Документ',),
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
